# docker-compose.yml
version: "3.8"
services:
  webserver:
    container_name: api
    restart: always
    build: 
      context: .
      dockerfile: ./src/Dockerfile
    depends_on:
      - database 
    environment:
      NODE_ENV: dev
      POSTGRES_HOST: database
    ports:
      - 8081:${APP_PORT}
    command: npm run dev
    volumes:
      - .:/usr/src/app
    networks:
      - bsocial

  database:
    container_name: postgres
    image: postgres
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - postgresDB:/data/postgres
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - bsocial

networks:
  bsocial:
    driver: bridge

volumes:
  postgresDB: {}
